// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @typedef {import('./models').main.Person} mainPerson
 */


window.go = window.go || {};
window.go.main = {
    App: {

		/**
		 * App.GetTransalteMap
		 *
		 *
		 * @returns {Promise<string>}
		 **/
	    GetTransalteMap: function() { return wails.CallByID(3159850429, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.GetTransalteWay
		 *
		 *
		 * @returns {Promise<string>}
		 **/
	    GetTransalteWay: function() { return wails.CallByID(3877427008, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.Greet
		 * Greet greets a person
		 * @param name {string}
		 * @returns {Promise<string>}
		 **/
	    Greet: function(name) { return wails.CallByID(2659711170, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.GreetPerson
		 * GreetPerson greets a person
		 * @param person {mainPerson}
		 * @returns {Promise<string>}
		 **/
	    GreetPerson: function(person) { return wails.CallByID(4207695951, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.Hide
		 * Hide 通过名字控制窗口事件
		 * @param windowName {string}
		 * @returns {Promise<void>}
		 **/
	    Hide: function(windowName) { return wails.CallByID(3538035797, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.MyFetch
		 * MyFetch URl
		 * @param URL {string}
 * @param content {map}
		 * @returns {Promise<>}
		 **/
	    MyFetch: function(URL, content) { return wails.CallByID(2071126117, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.SetTransalteWay
		 *
		 * @param translateWay {string}
		 * @returns {Promise<void>}
		 **/
	    SetTransalteWay: function(translateWay) { return wails.CallByID(1606326012, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.Show
		 * Show 通过名字控制窗口事件
		 * @param windowName {string}
		 * @returns {Promise<void>}
		 **/
	    Show: function(windowName) { return wails.CallByID(2781088484, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.Transalte
		 *
		 * @param queryText {string}
 * @param fromLang {string}
 * @param toLang {string}
		 * @returns {Promise<string>}
		 **/
	    Transalte: function(queryText, fromLang, toLang) { return wails.CallByID(3553729015, ...Array.prototype.slice.call(arguments, 0)); },

		/**
		 * App.TranslateShow
		 *
		 * @param height {number}
		 * @returns {Promise<void>}
		 **/
	    TranslateShow: function(height) { return wails.CallByID(1077762948, ...Array.prototype.slice.call(arguments, 0)); },
    },
};
