// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeyBoard() {
  return window['go']['main']['App']['GetKeyBoard']();
}

export function GetTransalteMap() {
  return window['go']['main']['App']['GetTransalteMap']();
}

export function GetTransalteWay() {
  return window['go']['main']['App']['GetTransalteWay']();
}

export function MyFetch(arg1, arg2) {
  return window['go']['main']['App']['MyFetch'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SendDataToJS(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDataToJS'](arg1, arg2, arg3);
}

export function SetKeyBoard(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetKeyBoard'](arg1, arg2, arg3);
}

export function SetTransalteWay(arg1) {
  return window['go']['main']['App']['SetTransalteWay'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function Transalte(arg1) {
  return window['go']['main']['App']['Transalte'](arg1);
}
