// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureSelectedScreen(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function GetKeyBoard():Promise<Array<string>>;

export function GetTransalteMap():Promise<string>;

export function GetTransalteWay():Promise<string>;

export function MyFetch(arg1:string,arg2:{[key: string]: any}):Promise<any>;

export function Quit():Promise<void>;

export function SendDataToJS(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetKeyBoard(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetTransalteWay(arg1:string):Promise<void>;

export function Show():Promise<void>;

export function Transalte(arg1:string,arg2:string,arg3:string):Promise<void>;
