// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeyBoard() {
  return window['go']['main']['App']['GetKeyBoard']();
}

export function GetTransalteList() {
  return window['go']['main']['App']['GetTransalteList']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SendDataToJS(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDataToJS'](arg1, arg2, arg3);
}

export function SetKeyBoard(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetKeyBoard'](arg1, arg2, arg3);
}

export function SetTransalteList(arg1) {
  return window['go']['main']['App']['SetTransalteList'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}
